<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_address_invalid'] = 'Address is invalid.';
$lang['bandwidth_advanced_rule'] = 'Advanced Rule';
$lang['bandwidth_advanced_rules'] = 'Advanced Rules';
$lang['bandwidth_app_description'] = 'Bandwidth Manager is an essential tool to manage the performance of the entire network.  You can ensure that services such as web browsing, VoIP, SSH and others are guaranteed enough bandwidth.';
$lang['bandwidth_app_name'] = 'Bandwidth Manager';
$lang['bandwidth_bandwidth'] = 'Bandwidth';
$lang['bandwidth_basic_rule'] = 'Basic Rule';
$lang['bandwidth_basic_rules'] = 'Basic Rules';
$lang['bandwidth_ceiling'] = 'Ceiling';
$lang['bandwidth_configuration_file_missing'] = 'Configuration file is missing.';
$lang['bandwidth_destination'] = 'Destination';
$lang['bandwidth_direction'] = 'Direction';
$lang['bandwidth_direction_invalid'] = 'Direction is invalid.';
$lang['bandwidth_download_(kilobits_s)'] = 'Download (kilobits/s)';
$lang['bandwidth_flowing_from_network'] = 'Flowing from the network';
$lang['bandwidth_flowing_from_system'] = 'Flowing from the system';
$lang['bandwidth_flowing_to_network'] = 'Flowing to the network';
$lang['bandwidth_flowing_to_system'] = 'Flowing to the system';
$lang['bandwidth_greed'] = 'Greed';
$lang['bandwidth_ip_or_hostname'] = 'IP or Hostname';
$lang['bandwidth_kilobits_s'] = 'kilobits/s';
$lang['bandwidth_limit'] = 'Limit';
$lang['bandwidth_match_address'] = 'Match Address';
$lang['bandwidth_match_port'] = 'Match Port';
$lang['bandwidth_mode'] = 'Mode';
$lang['bandwidth_mode_invalid'] = 'Mode is invalid.';
$lang['bandwidth_network_interface'] = 'Network Interface';
$lang['bandwidth_network_interface_invalid'] = 'Network interface is invalid.';
$lang['bandwidth_network_interface_settings'] = 'Network Interface Settings';
$lang['bandwidth_network_interfaces'] = 'Network Interfaces';
$lang['bandwidth_priority_invalid'] = 'Priority is invalid.';
$lang['bandwidth_rate'] = 'Rate';
$lang['bandwidth_rate_invalid'] = 'Rate is invalid.';
$lang['bandwidth_rate_out_of_range'] = 'Rate is out of range.';
$lang['bandwidth_reserve'] = 'Reserve';
$lang['bandwidth_rule'] = 'Rule';
$lang['bandwidth_service'] = 'Service';
$lang['bandwidth_source'] = 'Source';
$lang['bandwidth_tooltip_description'] = 'If you would like to find out your real world bandwidth speeds, please check the User Guide for speed test tools.';
$lang['bandwidth_type'] = 'Type';
$lang['bandwidth_type_invalid'] = 'Bandwidth type is invalid.';
$lang['bandwidth_upload_(kilobits_s)'] = 'Upload (kilobits/s)';
