<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_address_invalid'] = 'Address is invalid.';
$lang['bandwidth_advanced_rule'] = 'Advanced Rule';
$lang['bandwidth_advanced_rules'] = 'Advanced Rules';
$lang['bandwidth_advanced_rules_unvailable_in_standalone'] = 'Дополнительные правила пропускной способности не применяются к системам в автономном режиме.';
$lang['bandwidth_app_description'] = 'Менеджер объема трафика является важным инструментом для управления производительностью всей сети.  Вы можете обеспечить сервисам таким как веб-браузер, VoIP, SSH и других, достаточную пропускную способность.';
$lang['bandwidth_app_name'] = 'Менеджер объема трафика';
$lang['bandwidth_bandwidth'] = 'Bandwidth';
$lang['bandwidth_basic_rule'] = 'Основное правило';
$lang['bandwidth_basic_rules'] = 'Основные правила';
$lang['bandwidth_ceiling'] = 'Ceiling';
$lang['bandwidth_configuration_file_missing'] = 'Configuration file is missing.';
$lang['bandwidth_destination'] = 'Destination';
$lang['bandwidth_direction'] = 'Direction';
$lang['bandwidth_direction_invalid'] = 'Direction is invalid.';
$lang['bandwidth_download_(kilobits_s)'] = 'Скачано (килобит/с)';
$lang['bandwidth_flowing_from_network'] = 'Flowing from the network';
$lang['bandwidth_flowing_from_system'] = 'Flowing from the system';
$lang['bandwidth_flowing_to_network'] = 'Flowing to the network';
$lang['bandwidth_flowing_to_system'] = 'Flowing to the system';
$lang['bandwidth_greed'] = 'Greed';
$lang['bandwidth_ip_or_hostname'] = 'IP или имя хоста';
$lang['bandwidth_kilobits_s'] = 'килобит/с';
$lang['bandwidth_limit'] = 'Лимит';
$lang['bandwidth_match_address'] = 'Match Address';
$lang['bandwidth_match_port'] = 'Match Port';
$lang['bandwidth_mode'] = 'Режим';
$lang['bandwidth_mode_invalid'] = 'Mode is invalid.';
$lang['bandwidth_network_interface'] = 'Сетевой интерфейс';
$lang['bandwidth_network_interface_invalid'] = 'Network interface is invalid.';
$lang['bandwidth_network_interface_settings'] = 'Настройки сетевого интерфейса';
$lang['bandwidth_network_interfaces'] = 'Сетевые интерфейсы';
$lang['bandwidth_priority_invalid'] = 'Priority is invalid.';
$lang['bandwidth_rate'] = 'Rate';
$lang['bandwidth_rate_invalid'] = 'Rate is invalid.';
$lang['bandwidth_rate_out_of_range'] = 'Rate is out of range.';
$lang['bandwidth_reserve'] = 'Резервный';
$lang['bandwidth_rule'] = 'Правило';
$lang['bandwidth_service'] = 'Сервис';
$lang['bandwidth_source'] = 'Источник';
$lang['bandwidth_tooltip_description'] = 'Если вы хотите узнать вашу реальную скорость пропускной способности, проверьте Руководство пользователя на инструмент тестирования скорости.';
$lang['bandwidth_type'] = 'Тип';
$lang['bandwidth_type_invalid'] = 'Тип пропускной способности недействителен.';
$lang['bandwidth_upload_(kilobits_s)'] = 'Загружено (килобит/с)';
