<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_address_invalid'] = 'Adressen är ogiltig.';
$lang['bandwidth_advanced_rule'] = 'Avancerade regel';
$lang['bandwidth_advanced_rules'] = 'Avancerade regler';
$lang['bandwidth_advanced_rules_unvailable_in_standalone'] = 'Advanced bandwidth rules are not applicable to systems in standalone mode.';
$lang['bandwidth_app_description'] = 'Bandbreddshanteraren är ett viktigt verktyg för att hantera prestandan för hela nätverket.   Du kan göra så att tjänster som att surfa på nätet, VOIP, SSH och andra tjänster garanteras tillräcklig bandbredd.';
$lang['bandwidth_app_name'] = 'Bandbreddshanteraren';
$lang['bandwidth_bandwidth'] = 'Bandbredd';
$lang['bandwidth_basic_rule'] = 'Grundläggande regel';
$lang['bandwidth_basic_rules'] = 'Grundläggande regler';
$lang['bandwidth_ceiling'] = 'Tak';
$lang['bandwidth_configuration_file_missing'] = 'Konfigurationsfilen saknas.';
$lang['bandwidth_destination'] = 'Mål';
$lang['bandwidth_direction'] = 'Riktning';
$lang['bandwidth_direction_invalid'] = 'Riktningen är ogiltig.';
$lang['bandwidth_download_(kilobits_s)'] = 'Nerladdning (kilobits/s)';
$lang['bandwidth_flowing_from_network'] = 'Flöde från nätverket';
$lang['bandwidth_flowing_from_system'] = 'Flöde från systemet';
$lang['bandwidth_flowing_to_network'] = 'Flöde till nätverket';
$lang['bandwidth_flowing_to_system'] = 'Flöde till systemet';
$lang['bandwidth_greed'] = 'Girighet';
$lang['bandwidth_ip_or_hostname'] = 'IP eller värdnamn';
$lang['bandwidth_kilobits_s'] = 'kilobits/s';
$lang['bandwidth_limit'] = 'Gräns';
$lang['bandwidth_match_address'] = 'Sammanfoga adresser';
$lang['bandwidth_match_port'] = 'Sammanfoga portar';
$lang['bandwidth_mode'] = 'Mod';
$lang['bandwidth_mode_invalid'] = 'Moden är ogiltig';
$lang['bandwidth_network_interface'] = 'Nätverksinterfac';
$lang['bandwidth_network_interface_invalid'] = 'Nätverksinterfacet är ogiltigt';
$lang['bandwidth_network_interface_settings'] = 'Nätverksinterfacets inställningar';
$lang['bandwidth_network_interfaces'] = 'Nätverksinterface';
$lang['bandwidth_priority_invalid'] = 'Prioriteten är ogiltig.';
$lang['bandwidth_rate'] = 'Förhållande';
$lang['bandwidth_rate_invalid'] = 'Förhållandet är ogiltigt.';
$lang['bandwidth_rate_out_of_range'] = 'Förhållandet är utanför tillåtet område.';
$lang['bandwidth_reserve'] = 'Reserv';
$lang['bandwidth_rule'] = 'Regel';
$lang['bandwidth_service'] = 'Tjänst';
$lang['bandwidth_source'] = 'Källa';
$lang['bandwidth_tooltip_description'] = 'Om du vill få reda på ditt verkliga bandbredd, titta i användarguiden för testverktyg.';
$lang['bandwidth_type'] = 'Typ';
$lang['bandwidth_type_invalid'] = 'Bandbreddstyp är ogiltig.';
$lang['bandwidth_upload_(kilobits_s)'] = 'Uppladdning (kilobits/s)';
