<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_address_invalid'] = 'Podany adres jest nieprawidłowy.';
$lang['bandwidth_advanced_rule'] = 'Reguła zaawansowana';
$lang['bandwidth_advanced_rules'] = 'Reguły zaawansowane';
$lang['bandwidth_advanced_rules_unvailable_in_standalone'] = 'Advanced bandwidth rules are not applicable to systems in standalone mode.';
$lang['bandwidth_app_description'] = 'Menadżer pasma jest podstawowym narzędziem do zarządzania wydajnością całej sieci.  Możesz zapewnić usługom takim jak przeglądanie internetu, VoIP, SSH i innym gwarancję wystarczającego pasma.';
$lang['bandwidth_app_name'] = 'Menadżer pasma';
$lang['bandwidth_bandwidth'] = 'Pasmo';
$lang['bandwidth_basic_rule'] = 'Reguła podstawowa';
$lang['bandwidth_basic_rules'] = 'Reguły podstawowe';
$lang['bandwidth_ceiling'] = 'Pułap';
$lang['bandwidth_configuration_file_missing'] = 'Brakuje pliku konfiguracyjnego.';
$lang['bandwidth_destination'] = 'Lokalizacja docelowa';
$lang['bandwidth_direction'] = 'Kierunek';
$lang['bandwidth_direction_invalid'] = 'Podany kierunek jest nieprawidłowy.';
$lang['bandwidth_download_(kilobits_s)'] = 'Pobieranie (kilobitów/s)';
$lang['bandwidth_flowing_from_network'] = 'Wychodzący z sieci';
$lang['bandwidth_flowing_from_system'] = 'Wychodzący z systemu';
$lang['bandwidth_flowing_to_network'] = 'Wchodzący do sieci';
$lang['bandwidth_flowing_to_system'] = 'Wchodzący do systemu';
$lang['bandwidth_greed'] = 'Chciwość';
$lang['bandwidth_ip_or_hostname'] = 'Adres IP lub nazwa hosta';
$lang['bandwidth_kilobits_s'] = 'kilobitów/s';
$lang['bandwidth_limit'] = 'Limit';
$lang['bandwidth_match_address'] = 'Dopasuj adres';
$lang['bandwidth_match_port'] = 'Dopasuj port';
$lang['bandwidth_mode'] = 'Tryb';
$lang['bandwidth_mode_invalid'] = 'Tryb jest nieprawidłowy.';
$lang['bandwidth_network_interface'] = 'Interfejs sieciowy';
$lang['bandwidth_network_interface_invalid'] = 'Interfejs sieciowy jest nieprawidłowy.';
$lang['bandwidth_network_interface_settings'] = 'Interfejs sieciowy';
$lang['bandwidth_network_interfaces'] = 'Interfejsy sieciowe';
$lang['bandwidth_priority_invalid'] = 'Podany priorytet jest nieprawidłowy.';
$lang['bandwidth_rate'] = 'Prędkość';
$lang['bandwidth_rate_invalid'] = 'Podana prędkość jest nieprawidłowa.';
$lang['bandwidth_rate_out_of_range'] = 'Podana prędkość nie mieści się w zakresie.';
$lang['bandwidth_reserve'] = 'Rezerwacja';
$lang['bandwidth_rule'] = 'Reguła';
$lang['bandwidth_service'] = 'Usługa';
$lang['bandwidth_source'] = 'Lokalizacja źródłowa';
$lang['bandwidth_tooltip_description'] = 'Jeżeli chciałbyś poznać realne prędkości internetu, prosimy zapoznać się z przewodnikiem użytkownika, gdzie znajdują się odnośniki do narzędzi mierzących prędkość internetu.';
$lang['bandwidth_type'] = 'Typ';
$lang['bandwidth_type_invalid'] = 'Typ pasma jest nieprawidłowy.';
$lang['bandwidth_upload_(kilobits_s)'] = 'Wysyłanie (kilobitów/s)';
